name: install

on:
  workflow_call:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    concurrency: install-${{ github.ref }}
    steps:
      - name: Run `git checkout`
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.14

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('setup.py') }}

      - name: Install dependencies
        run: |
          python3 -m venv env
          source ./env/bin/activate
          python3 setup.py install
