name: install

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    name: Lint on ${{ github.ref }}
    runs-on: ubuntu-latest
    concurrency: install-${{ github.ref }}
    steps:
      - name: Run `git checkout`
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          python3 -m venv env
          source ./env/bin/activate
          python3 setup.py install
          pip3 install pylint
          pylint hello/ --fail-under 7


      # - name: Run lint
      #   uses: ricardochaves/python-lint@v1.4.0
      #   env:
      #     FLASK_APP: hello
