name: Test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency: install-${{ github.ref }}
    steps:
      - name: Run `git checkout`
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          python3 -m venv env
          source ./env/bin/activate
          python3 setup.py install
          pip3 install pytest
          pytest
