name: test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ github.ref }}
    runs-on: ubuntu-latest
    concurrency: install-${{ github.ref }}
    steps:
      - name: Run `git checkout`
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          python3 -m venv env
          source ./env/bin/activate
          python3 setup.py install
          pip3 install pytest
          pytest

      # - name: Install pytest
      #   run: pip3 install pytest
      #
      # - name: Run tests
      #   run: |
      #     ls -al
      #     pytest
      #   timeout-minutes: 10
      #   env:
      #     FLASK_APP: hello
